# Generated by Django 5.1.5 on 2025-02-05 03:34

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Evento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Proveedor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200, unique=True)),
                ('contacto', models.CharField(max_length=100)),
            ],
            options={
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='DetalleGasto',
            fields=[
                ('folio', models.AutoField(primary_key=True, serialize=False)),
                ('fecha', models.DateTimeField(default=django.utils.timezone.now)),
                ('importe', models.DecimalField(decimal_places=2, max_digits=10)),
                ('concepto', models.CharField(choices=[('pago', 'Pago'), ('anticipo', 'Anticipo'), ('prestamo', 'Prestamo'), ('adeudo', 'Adeudo'), ('apertura', 'Apertura Cta'), ('devolucion', 'Devolucion')], default='pago', max_length=200)),
                ('tipo_gasto', models.CharField(choices=[('efe', 'Efectivo'), ('tdp', 'Transf. Directa Platinum'), ('puente', 'Transf. Puente'), ('deposito', 'Deposito a Proveedor'), ('caja', 'Caja Chica'), ('boveda', 'Boveda')], default='efe', max_length=100)),
                ('comentarios', models.TextField(blank=True, null=True)),
                ('evento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.evento')),
                ('proveedor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.proveedor')),
            ],
        ),
    ]
