# Generated by Django 5.1.6 on 2025-11-24 02:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_categoria_concepto'),
    ]

    operations = [
        migrations.AddField(
            model_name='detallegasto',
            name='concepto2',
            field=models.ForeignKey(default=215, on_delete=django.db.models.deletion.CASCADE, to='myapp.concepto'),
        ),
    ]
