# Generated by Django 5.1.6 on 2025-11-30 14:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_detallegasto_concepto2'),
    ]

    operations = [
        migrations.AddField(
            model_name='detallegasto',
            name='estatus',
            field=models.CharField(choices=[('ok', 'OK'), ('not_ok', 'Not OK')], default='ok', max_length=10),
        ),
        migrations.AlterField(
            model_name='detallegasto',
            name='concepto2',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.concepto'),
        ),
    ]
