# Generated by Django 5.1.6 on 2025-12-07 17:51

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_detallegasto_estatus_alter_detallegasto_concepto2'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConceptoIngresos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('concepto', models.CharField(max_length=200, unique=True)),
                ('estatus', models.CharField(choices=[('ACTIVO', 'Activo'), ('INACTIVO', 'Inactivo')], default='ACTIVO', max_length=10)),
            ],
        ),
        migrations.AddField(
            model_name='evento',
            name='estatus',
            field=models.CharField(choices=[('abierto', 'Abierto'), ('cerrado', 'Cerrado'), ('cancelado', 'Cancelado')], default='abierto', max_length=10),
        ),
        migrations.CreateModel(
            name='Graduado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=150)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('telefono', models.CharField(max_length=20, validators=[django.core.validators.RegexValidator('^\\+?\\d{7,15}$', 'Formato de teléfono inválido')])),
                ('evento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.evento')),
            ],
        ),
        migrations.CreateModel(
            name='DetalleIngresos',
            fields=[
                ('folio', models.AutoField(primary_key=True, serialize=False)),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('importe', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('forma_pago', models.CharField(choices=[('EF', 'Efectivo'), ('TR', 'Transferencia'), ('MP', 'Mercado Pago'), ('DS', 'Depósito en sucursal'), ('PL', 'Pago en línea')], default='efe', max_length=100)),
                ('comentarios', models.TextField(blank=True, null=True)),
                ('concepto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.conceptoingresos')),
                ('evento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.evento')),
                ('graduado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.graduado')),
            ],
        ),
    ]
