# Generated by Django 5.1.6 on 2025-12-13 22:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_conceptoingresos_evento_estatus_graduado_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='evento',
            name='fecha_evento',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha del evento'),
        ),
    ]
